---
name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - name: ✔ Check out
        uses: actions/checkout@v4
      - name: 🌿 Set up Bazel
        uses: bazel-contrib/setup-bazel@0.8.4
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: 🔨 Test
        run: bazel test //...
